[manifest]
version = "1.0.0"
priority = 0

# Add the wonder header before the main box
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "desc_from_rows(AUT.main),"
position = "before"
match_indent = true
payload = """
card.ability and card.ability.set == "paperback_ticket_to_ride" and {
  n = G.UIT.R,
  config = { align = "cm", colour = PB_UTIL.TICKET_GRADIENT, r = 0.1, padding = 0.04 },
  nodes = {
    {
      n = G.UIT.R,
      config = { align = "tm", minh = 0.36, padding = 0.03 },
      nodes = {
        {
          n = G.UIT.T,
          config = { 
            text = localize('paperback_ticket_wonder'),
            scale = 0.5,
            colour = G.C.UI.TEXT_LIGHT
          }
        }
      }
    }
  }
} or nil,
"""

# Before each multibox of a ticket add the stage headers
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "multi_boxes[#multi_boxes+1] = desc_from_rows(box)"
position = "before"
match_indent = true
payload = """
if card.ability and card.ability.set == "paperback_ticket_to_ride" then
  multi_boxes[#multi_boxes+1] = {
    n = G.UIT.R,
    config = { align = "cm", colour = G.C.PAPERBACK_TICKET_STAGE, r = 0.1, padding = 0.04 },
    nodes = {
      {
        n = G.UIT.R,
        config = { align = "tm", minh = 0.36, padding = 0.03 },
        nodes = {
          {
            n = G.UIT.T,
            config = { 
              text = localize {
                type = "variable",
                key = "paperback_ticket_stage",
                vars = { i, #AUT.multi_box }
              },
              scale = 0.3,
              colour = G.C.UI.TEXT_LIGHT
            }
          }
        }
      }
    }
  }
end
"""
